import struct
import math
import os
import zipfile

def create_segment_polygon(length, width):
    """
    Returns 2D polygon vertices for a 45-degree chamfered 7-segment shape.
    Centered at (0, 0).
    """
    half_l = length / 2.0
    half_w = width / 2.0
    
    # 6-sided hexagon polygon
    return [
        (-half_l, 0.0),
        (-half_l + half_w, -half_w),
        (half_l - half_w, -half_w),
        (half_l, 0.0),
        (half_l - half_w, half_w),
        (-half_l + half_w, half_w)
    ]

def transform_polygon(poly, tx, ty, rotate_deg=0):
    rad = math.radians(rotate_deg)
    cos_a = math.cos(rad)
    sin_a = math.sin(rad)
    
    transformed = []
    for x, y in poly:
        # Rotate
        rx = x * cos_a - y * sin_a
        ry = x * sin_a + y * cos_a
        # Translate
        transformed.append((rx + tx, ry + ty))
    return transformed

def triangulate_polygon_prism(poly_2d, z_min, z_max):
    """
    Triangulates a 2D convex/simple polygon extruded from z_min to z_max.
    Returns list of triangles, each triangle is ((x1,y1,z1), (x2,y2,z2), (x3,y3,z3)).
    """
    triangles = []
    n = len(poly_2d)
    
    # Bottom face (z_min, normal pointing down)
    # Fan triangulation from vertex 0
    for i in range(1, n - 1):
        triangles.append((
            (poly_2d[0][0], poly_2d[0][1], z_min),
            (poly_2d[i+1][0], poly_2d[i+1][1], z_min),
            (poly_2d[i][0], poly_2d[i][1], z_min)
        ))
        
    # Top face (z_max, normal pointing up)
    # Fan triangulation from vertex 0
    for i in range(1, n - 1):
        triangles.append((
            (poly_2d[0][0], poly_2d[0][1], z_max),
            (poly_2d[i][0], poly_2d[i][1], z_max),
            (poly_2d[i+1][0], poly_2d[i+1][1], z_max)
        ))
        
    # Side quads (2 triangles per segment)
    for i in range(n):
        next_i = (i + 1) % n
        p1 = poly_2d[i]
        p2 = poly_2d[next_i]
        
        # Tri 1: (p1_bot, p2_bot, p2_top)
        triangles.append((
            (p1[0], p1[1], z_min),
            (p2[0], p2[1], z_min),
            (p2[0], p2[1], z_max)
        ))
        # Tri 2: (p1_bot, p2_top, p1_top)
        triangles.append((
            (p1[0], p1[1], z_min),
            (p2[0], p2[1], z_max),
            (p1[0], p1[1], z_max)
        ))
        
    return triangles

def write_binary_stl(filepath, triangles):
    header = b"Generated by Antigravity - 7Segment Dual-Layer Diffuser" + b"\x00" * 25
    header = header[:80]
    
    with open(filepath, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", len(triangles)))
        
        for tri in triangles:
            p1, p2, p3 = tri
            # Calculate normal
            u = (p2[0]-p1[0], p2[1]-p1[1], p2[2]-p1[2])
            v = (p3[0]-p1[0], p3[1]-p1[1], p3[2]-p1[2])
            nx = u[1]*v[2] - u[2]*v[1]
            ny = u[2]*v[0] - u[0]*v[2]
            nz = u[0]*v[1] - u[1]*v[0]
            norm = math.sqrt(nx*nx + ny*ny + nz*nz)
            if norm > 1e-9:
                nx /= norm
                ny /= norm
                nz /= norm
            else:
                nx, ny, nz = 0.0, 0.0, 1.0
                
            f.write(struct.pack("<fff", nx, ny, nz))
            f.write(struct.pack("<fff", p1[0], p1[1], p1[2]))
            f.write(struct.pack("<fff", p2[0], p2[1], p2[2]))
            f.write(struct.pack("<fff", p3[0], p3[1], p3[2]))
            f.write(struct.pack("<H", 0))

def generate_7segment_polygons():
    pitch_x = 92.0
    pitch_y_top = 92.0
    pitch_y_bot = 92.0
    
    total_seg_w = 18.0
    total_seg_l_x = 104.0
    total_seg_l_y_top = 104.0
    total_seg_l_y_bot = 117.0
    
    poly_horiz_top = create_segment_polygon(total_seg_l_x, total_seg_w)
    poly_horiz_mid = create_segment_polygon(total_seg_l_x, total_seg_w)
    poly_horiz_bot = create_segment_polygon(total_seg_l_x, total_seg_w)
    
    poly_vert_top = create_segment_polygon(total_seg_l_y_top, total_seg_w)
    poly_vert_bot = create_segment_polygon(total_seg_l_y_bot, total_seg_w)
    
    all_polys = [
        # Segment A (Top horizontal)
        transform_polygon(poly_horiz_top, 0, pitch_y_top, 0),
        # Segment B (Top-Right vertical)
        transform_polygon(poly_vert_top, pitch_x/2, pitch_y_top/2, 90),
        # Segment C (Bottom-Right vertical)
        transform_polygon(poly_vert_bot, pitch_x/2, -pitch_y_bot/2, 90),
        # Segment D (Bottom horizontal)
        transform_polygon(poly_horiz_bot, 0, -pitch_y_bot, 0),
        # Segment E (Bottom-Left vertical)
        transform_polygon(poly_vert_bot, -pitch_x/2, -pitch_y_bot/2, 90),
        # Segment F (Top-Left vertical)
        transform_polygon(poly_vert_top, -pitch_x/2, pitch_y_top/2, 90),
        # Segment G (Middle horizontal)
        transform_polygon(poly_horiz_mid, 0, 0, 0),
    ]
    return all_polys

def main():
    out_dir = r"c:\Users\geert\Documents\Github\7segment\3d_models"
    os.makedirs(out_dir, exist_ok=True)
    
    # 1. Single segment test pieces (Length 104mm, Width 18mm)
    single_poly = [create_segment_polygon(104.0, 18.0)]
    
    # Layer 1: White (0.0 to 0.2 mm)
    single_white_tris = []
    for p in single_poly:
        single_white_tris.extend(triangulate_polygon_prism(p, 0.0, 0.2))
    write_binary_stl(os.path.join(out_dir, "single_segment_0.2mm_layer1_WHITE.stl"), single_white_tris)
    
    # Layer 2: Transparent (0.2 to 0.8 mm)
    single_transp_tris = []
    for p in single_poly:
        single_transp_tris.extend(triangulate_polygon_prism(p, 0.2, 0.8))
    write_binary_stl(os.path.join(out_dir, "single_segment_0.6mm_layer2_TRANSPARENT.stl"), single_transp_tris)
    
    # Single Solid STL (0.0 to 0.8 mm)
    single_solid_tris = []
    for p in single_poly:
        single_solid_tris.extend(triangulate_polygon_prism(p, 0.0, 0.8))
    write_binary_stl(os.path.join(out_dir, "single_segment_0.8mm_SOLID.stl"), single_solid_tris)
    
    # 2. Full 7-Segment Diffuser
    seven_polys = generate_7segment_polygons()
    
    # Layer 1: White (0.0 to 0.2 mm)
    seven_white_tris = []
    for p in seven_polys:
        seven_white_tris.extend(triangulate_polygon_prism(p, 0.0, 0.2))
    write_binary_stl(os.path.join(out_dir, "7segment_diffuser_0.2mm_layer1_WHITE.stl"), seven_white_tris)
    
    # Layer 2: Transparent (0.2 to 0.8 mm)
    seven_transp_tris = []
    for p in seven_polys:
        seven_transp_tris.extend(triangulate_polygon_prism(p, 0.2, 0.8))
    write_binary_stl(os.path.join(out_dir, "7segment_diffuser_0.6mm_layer2_TRANSPARENT.stl"), seven_transp_tris)
    
    # Full Solid STL (0.0 to 0.8 mm)
    seven_solid_tris = []
    for p in seven_polys:
        seven_solid_tris.extend(triangulate_polygon_prism(p, 0.0, 0.8))
    write_binary_stl(os.path.join(out_dir, "7segment_diffuser_0.8mm_SOLID.stl"), seven_solid_tris)
    
    print("All STL files successfully created in:", out_dir)

if __name__ == "__main__":
    main()
