[platformio]
default_envs = esp32s3_zero

[env:esp32s3_zero]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = default.csv
framework = arduino
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

