[platformio]
default_envs = esp32c3_supermini

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
upload_port = COM12
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino
	makuna/RTC @ ^2.4.3

