[platformio]
default_envs = esp32s3_zero_combined

# ==============================================================================
# ESP32-S3 Zero (Waveshare)
# ==============================================================================
[env:esp32s3_zero_combined]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
framework = arduino
build_src_filter = -<*> +<main_combined.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32s3_zero]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
framework = arduino
build_src_filter = -<*> +<main.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32s3_zero_clock]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
framework = arduino
build_src_filter = -<*> +<main_clock.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32s3_zero_button]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
framework = arduino
build_src_filter = -<*> +<main_button_Setsandmatch.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32s3_zero_button_4digits]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_mode = dio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv
framework = arduino
build_src_filter = -<*> +<main_button_4digits.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

# ==============================================================================
# ESP32-C3 SuperMini
# ==============================================================================
[env:esp32c3_supermini_combined]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_combined.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini_clock]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_clock.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini_button]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_button_Setsandmatch.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini_button_4digits]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_button_4digits.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini_dual_4digits]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_dual_4digits.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
extra_scripts = pre:scripts/patch_neopixel.py
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:esp32c3_supermini_test88]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.partitions = min_spiffs.csv
build_src_filter = -<*> +<main_test_88.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel

# ==============================================================================
# Lolin S3 Mini
# ==============================================================================
[env:lolin_s3_mini_combined]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = -<*> +<main_combined.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = -<*> +<main.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini_clock]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = -<*> +<main_clock.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini_button]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = -<*> +<main_button_Setsandmatch.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3

[env:lolin_s3_mini_button_4digits]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = -<*> +<main_button_4digits.cpp>
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit NeoPixel
	h2zero/NimBLE-Arduino @ ^1.4.2
	makuna/RTC @ ^2.4.3
